// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDif_ubGbkvo8Z9exyIE4d2CQerI8OXB8',
    appId: '1:211282086351:web:3f261fdc0d5bc82e4eaaba',
    messagingSenderId: '211282086351',
    projectId: 'padigosk-chat-app',
    authDomain: 'padigosk-chat-app.firebaseapp.com',
    storageBucket: 'padigosk-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgXDoqULouhThJTvx-kbeUWtr74XFiaLA',
    appId: '1:211282086351:android:e3a0e751f0879b9b4eaaba',
    messagingSenderId: '211282086351',
    projectId: 'padigosk-chat-app',
    storageBucket: 'padigosk-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBoTpV-RpwfsDjyDV-I8SXhpU6ZVePNs',
    appId: '1:211282086351:ios:68a880a0a0c837d74eaaba',
    messagingSenderId: '211282086351',
    projectId: 'padigosk-chat-app',
    storageBucket: 'padigosk-chat-app.appspot.com',
    iosClientId: '211282086351-qs63vd9o17i21mpm9ra7mp51mi0n0l09.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
